### ISSUE TITLE
Use Python CLI to send a double via json-rpc service

### ISSUE THREAD

**Issue by paxos1977** [minorg/thryft#175]
I have a struct defined something like this:

    struct Type {
        double t;
    }

I'm attempting to invoke a generated json-rpc service (which takes the type as a parameter) using the Python CLI tool, but I'm getting the following error:

> AttributeError: 'JsonInputProtocol' object has no attribute 'read_double'

Is this a supported use case? If not, what's the recommended way to get doubles into a service? The backend Java code _must_ work with doubles.

**Comment by minorg** [comment]
Fixed on develop.
